name: "Event Store"
description: "The open-source, functional database with Complex Event Processing in JavaScript."
url: "http://geteventstore.com"
markdown: rdiscount
permalink: /blog/:year:month:day/:title/index.html
