name: "Event Store"
description: "The open-source, functional database with Complex Event Processing in JavaScript."
url: "http://tarvos.local:5757"
markdown: rdiscount
permalink: /blog/:year:month:day/:title/index.html
