name: "Event Store"
description: "The open-source, functional database with Complex Event Processing in JavaScript."
url: "http://geteventstore.dev"
permalink: /blog/:year:month:day/:title/index.html
markdown: redcarpet
highlighter: pygments